# Update notifications
notifications:
  email:
    on_success: never

# Enable C support
language: c

dist: bionic

sudo: required

addons:
  apt:
    packages:
      - ninja-build
      - gcc-arm-none-eabi
      - libnewlib-arm-none-eabi

# Compiler selection
compiler:
  - gcc

os:
  - linux


# Build steps
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_TOOLCHAIN_FILE=./cmake/arm-none-eabi-gcc.cmake -G "Ninja" ..
  - cmake --build .
